### ISSUE TITLE
xADDomainController: Missing Ensure in MSFT_xADDomainController.schema.mof

### ISSUE THREAD

**Issue by jaymedavis** [PowerShell/xActiveDirectory#52]
I'm pretty sure we need to add `[read] String Ensure;` in MSFT_xADDomainController.schema.mof. Get-TargetResource in MSFT_xADDomainController.psm1 has Ensure in the return value, which is not specified in the schema file. 

This seems to have fixed it locally. Let me know if this sounds right and I will submit a PR.

**Comment by BrunoReboul** [comment]
I use the same fix locally, seems right from my experience.
If not fixed then Get-dsccompliance breaks, with error events 4097 and 4252 in operational log

**Comment by iainbrighton** [comment]
This should be fixed at the same time as #67

**Comment by Duffney** [comment]
This issue still isn't fixed, I ran into when resolving a different issue relating to the xActiveDirectory module. It is present in version Releasing version 2.10.0.0 and hasn't been updated on GitHub as of yet. Let's see if I can figure out this pull request thing. :) 
![capture](https://cloud.githubusercontent.com/assets/8146181/14829710/70de4462-0bb2-11e6-887e-596ff23554ca.PNG)

**Comment by iainbrighton** [comment]
That's the attitude! It's on my list but was waiting to Mr Greene to resolve his merge conflicts.

I see no reason not to proceed as other changes have since been pushed. If you need any help, just ask!

**Comment by TravisEz13** [comment]
@iainbrighton I've closed the 2 PRs and submitted an issue asking to port the smaller of the two.  I'm working with Mr Greene to resubmit the other request.

**Comment by johlju** [comment]
This issue has been resolved in a recent PR.
